template: true   # required for local templates
valuesFilePath: ./values.yml

resources: 
  - name: release_bundle_demo
    type: ReleaseBundle
    configuration:
      #sourceDistribution: myDist
      sourceDistribution:  {{ .Values.distributionIntegration }}
      name: demo_rb
      version: v1.0.0

  - name: signed_bundle_demo
    type: ReleaseBundle
    configuration:
      #sourceDistribution: myDist
      sourceDistribution:  {{ .Values.distributionIntegration }}
      name: demo_rb
      version: v1.0.0

  - name: distribution_rules_demo
    type: DistributionRule
    configuration:
      #sourceDistribution: myDist
      sourceDistribution:  {{ .Values.distributionIntegration }}
      serviceName: "*"
      siteName: "*"
      cityName: "*"
      countryCodes:
        - "CN"     

pipelines:
  - name: CD_Quickstart_demo
    steps:
      - name: bundle
        type: CreateReleaseBundle
        configuration:
          releaseBundleName: demo_rb
          releaseBundleVersion: v1.0.${run_number}
          dryRun: false
          sign: false
          description: "some random test description"
          inputResources:
            - name: image_build_info
              trigger: false
          outputResources:
            - name: release_bundle_demo
          releaseNotes:
            syntax: markdown
            content: |
              ## Heading
                * Bullet
                * Points

      - name: sign
        type: SignReleaseBundle
        configuration:
          inputResources:
            - name: release_bundle_demo
          outputResources:
            - name: signed_bundle_demo

      - name: distribute
        type: DistributeReleaseBundle
        configuration:
          dryRun: false
          inputResources:
            - name: signed_bundle_demo
            - name: distribution_rules_demo
